# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    identifier: research
    url: research
    weight: 10
  - name: People
    url: people
    weight: 20  
  - name: News
    url: post
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Resources
    url: resource
    weight: 50
 # - name: Contact
  #  url: contact
  #  weight: 60
  # - name: Climate change
  #   url: research/climate-change/
  #   weight: 10
  #   parent: research
  # - name: Eco-evo
  #   url: research/eco-evo/
  #   weight: 10
  #   parent: research
  # - name: Habitat
  #   url: research/habitat/
  #   weight: 10
  #   parent: research
  # - name: Social-ecological systems
  #   url: research/SES/
  #   weight: 10
  #   parent: research
  # - name: Recruitment
  #   url: research/recruitment/
  #   weight: 10
  #   parent: research
  # - name: Food webs
  #   url: research/food-webs/
  #   weight: 10
  #   parent: research