# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    identifier: research
    url: research
    weight: 10
  - name: People
    url: people
    weight: 20  
  - name: News
    url: post
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Contact
    url: contact
    weight: 50
  - name: Climate change
    url: research/climate-change/
    weight: 10
    parent: research